development:
  adapter: postgresql
  encoding: utf8
  database: people_and_stuff_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: people_and_stuff_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: people_and_stuff_production
  pool: 5
  username:
  password: