development:
  app_id: <%= ENV["FACEBOOK_APPID"] %>
  secret_key: <%= ENV["FACEBOOK_SECRET"] %>
test:
  app_id: <%= ENV["FACEBOOK_APPID"] %>
  secret_key: <%= ENV["FACEBOOK_SECRET"] %>
production:
  app_id: <%= ENV["FACEBOOK_APPID"] %>
  secret_key: <%= ENV["FACEBOOK_SECRET"] %>