require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DressesController do

  # This should return the minimal set of attributes required to create a valid
  # Dress. As you add validations to Dress, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "size" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DressesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dresses as @dresses" do
      dress = Dress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dresses).should eq([dress])
    end
  end

  describe "GET show" do
    it "assigns the requested dress as @dress" do
      dress = Dress.create! valid_attributes
      get :show, {:id => dress.to_param}, valid_session
      assigns(:dress).should eq(dress)
    end
  end

  describe "GET new" do
    it "assigns a new dress as @dress" do
      get :new, {}, valid_session
      assigns(:dress).should be_a_new(Dress)
    end
  end

  describe "GET edit" do
    it "assigns the requested dress as @dress" do
      dress = Dress.create! valid_attributes
      get :edit, {:id => dress.to_param}, valid_session
      assigns(:dress).should eq(dress)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dress" do
        expect {
          post :create, {:dress => valid_attributes}, valid_session
        }.to change(Dress, :count).by(1)
      end

      it "assigns a newly created dress as @dress" do
        post :create, {:dress => valid_attributes}, valid_session
        assigns(:dress).should be_a(Dress)
        assigns(:dress).should be_persisted
      end

      it "redirects to the created dress" do
        post :create, {:dress => valid_attributes}, valid_session
        response.should redirect_to(Dress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dress as @dress" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dress.any_instance.stub(:save).and_return(false)
        post :create, {:dress => { "size" => "invalid value" }}, valid_session
        assigns(:dress).should be_a_new(Dress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dress.any_instance.stub(:save).and_return(false)
        post :create, {:dress => { "size" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dress" do
        dress = Dress.create! valid_attributes
        # Assuming there are no other dresses in the database, this
        # specifies that the Dress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dress.any_instance.should_receive(:update_attributes).with({ "size" => "MyString" })
        put :update, {:id => dress.to_param, :dress => { "size" => "MyString" }}, valid_session
      end

      it "assigns the requested dress as @dress" do
        dress = Dress.create! valid_attributes
        put :update, {:id => dress.to_param, :dress => valid_attributes}, valid_session
        assigns(:dress).should eq(dress)
      end

      it "redirects to the dress" do
        dress = Dress.create! valid_attributes
        put :update, {:id => dress.to_param, :dress => valid_attributes}, valid_session
        response.should redirect_to(dress)
      end
    end

    describe "with invalid params" do
      it "assigns the dress as @dress" do
        dress = Dress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dress.any_instance.stub(:save).and_return(false)
        put :update, {:id => dress.to_param, :dress => { "size" => "invalid value" }}, valid_session
        assigns(:dress).should eq(dress)
      end

      it "re-renders the 'edit' template" do
        dress = Dress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dress.any_instance.stub(:save).and_return(false)
        put :update, {:id => dress.to_param, :dress => { "size" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dress" do
      dress = Dress.create! valid_attributes
      expect {
        delete :destroy, {:id => dress.to_param}, valid_session
      }.to change(Dress, :count).by(-1)
    end

    it "redirects to the dresses list" do
      dress = Dress.create! valid_attributes
      delete :destroy, {:id => dress.to_param}, valid_session
      response.should redirect_to(dresses_url)
    end
  end

end
